FROM python:3.9-slim

WORKDIR /fundist

COPY requirements-worker.txt requirements.txt
RUN pip install -r requirements.txt

COPY src/worker worker
COPY src/database database
COPY src/integrations integrations
COPY src/signup_processors signup_processors

CMD celery -A worker:app worker -c 4